config/routes.rb
TeacherHelper::Application.routes.draw do

  resources :lessons do
    member do
      post 'confirm'
      post 'accept'
      put 'reschedule'
    end
  end

  resources :students, only: [:index, :show] do
    resource :balance, only: [:show, :edit, :update],
      controller: 'StudentBalance'
  end

  resources :teachers do
    resource :balance
    resources :schedules
  end


  devise_for :teachers, path_prefix: 'd'

  devise_for :students, path_prefix: 'd'

  root :to => 'home#index'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :teacher
  attr_accessible :end_at, :recurring, :start_at, :title

  validates :start_at, :end_at, :teacher, :minutes_before_start,
    :minutes_before_end, presence: true
  validate :one_schedule_in_one_time

  # FIXME seems in some rare cases it may not work if we want to
  # not use validation (like in update_all)
  before_validation :calculate_minutes

  def as_json(options = {})
    # FIXME timezone issue
    beginning_of_week = options[:beginning_of_week] ||
      start_at.beginning_of_week.advance(hours: 4)

    start_datetime = beginning_of_week.advance(minutes: minutes_before_start)
    end_datetime = beginning_of_week.advance(minutes: minutes_before_end)

    {
      id: id,
      start: start_datetime,
      end: end_datetime,
      recurring: recurring
    }
  end

  private

  def calculate_minutes
    beginning_of_week = start_at.beginning_of_week
    self.minutes_before_start = (start_at - beginning_of_week) / 60
    self.minutes_before_end = (end_at - beginning_of_week) / 60

    self.recurring = true
    true
  end

  def one_schedule_in_one_time
    available = teacher.schedules.where{ |schedules|
      (schedules.minutes_before_start < self.minutes_before_end) &
      (schedules.minutes_before_end > self.minutes_before_start) &
      (schedules.id != self.id)
    }.blank?
    unless available
      errors.add(:base, 'conflict with other schedule')
    end
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < InheritedResources::Base
  load_and_authorize_resource
  respond_to :json, :html
  belongs_to :teacher

  def index
    index! do |format|
      # FIXME!!!! fix timezone issues
      format.json {
        opts = { beginning_of_week: Time.parse(params[:date_start]
                                              ).advance(hours: 4) }
        render json: collection.to_json(opts) 
      }
    end
  end

end

app/views/schedules/_form.html.haml
= simple_form_for(@schedule) do |f|
  = f.error_notification

  .form-inputs
    = f.association :teacher
    = f.input :title
    = f.input :start_at
    = f.input :end_at
    = f.input :recurring

  .form-actions
    = f.button :submit

app/views/schedules/edit.html.haml
%h1 Editing schedule

= render 'form'

= link_to 'Show', @schedule
\|
= link_to 'Back', schedules_path

app/views/schedules/index.html.haml
%h1 Listing schedules

%table
  %tr
    %th Teacher
    %th Title
    %th Start at
    %th End at
    %th Recurring
    %th
    %th
    %th

  - @schedules.each do |schedule|
    %tr
      %td= schedule.teacher
      %td= schedule.title
      %td= schedule.start_at
      %td= schedule.end_at
      %td= schedule.recurring
      %td= link_to 'Show', schedule
      %td= link_to 'Edit', edit_schedule_path(schedule)
      %td= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Schedule', new_schedule_path

app/views/schedules/new.html.haml
%h1 New schedule

= render 'form'

= link_to 'Back', schedules_path

app/views/schedules/show.html.haml
%p#notice= notice

%p
  %b Teacher:
  = @schedule.teacher
%p
  %b Title:
  = @schedule.title
%p
  %b Start at:
  = @schedule.start_at
%p
  %b End at:
  = @schedule.end_at
%p
  %b Recurring:
  = @schedule.recurring

= link_to 'Edit', edit_schedule_path(@schedule)
\|
= link_to 'Back', schedules_path