config/routes.rb
TeacherHelper::Application.routes.draw do

  resources :lessons do
    member do
      post 'confirm'
      post 'accept'
      put 'reschedule'
    end
  end

  resources :students, only: [:index, :show] do
    resource :balance, only: [:show, :edit, :update],
      controller: 'StudentBalance'
  end

  resources :teachers do
    resource :balance
    resources :schedules
  end


  devise_for :teachers, path_prefix: 'd'

  devise_for :students, path_prefix: 'd'

  root :to => 'home#index'
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base

  module STATUS
    PENDING = 'pending'
    UPCOMING = 'upcoming'
    COMPLETED = 'completed'

    NOT_STARTED = [PENDING, UPCOMING]
  end

  belongs_to :student
  belongs_to :teacher

  validates :start_at, :end_at, :teacher, :student, presence: true
  validate :no_conflicts_with_other_lessons
  validate :in_teacher_schedule
  validate :not_earlier_than_tomorrow
  validate :student_has_enough_money, on: :create
  validate :should_not_be_completed, on: :destroy

  attr_accessible :end_at, :teacher_id, :start_at, :title, :status

  before_create :set_pending_status
  after_create :notify_teacher_about_new_lesson
  before_create :withdraw_money
  before_destroy :notify_about_canceling
  before_destroy :return_money_to_student

  def as_json(options = {})
    {
      # FIXME weird id passed to fc
      # http://code.google.com/p/fullcalendar/issues/detail?id=940
      id: id.to_s + ?l,
      start: start_at.rfc822,
      end: end_at.rfc822,
      title: "Lesson with: #{student.name}, Status: #{status}",
      status: status,
      student: student
    }
  end

  # returns money object
  def cost
    teacher.price * (end_at - start_at) / 1.hour
  end

  def complete
    self.status = STATUS::COMPLETED
    if self.save
      LessonMailer.lesson_completed(self).deliver
      teacher.balance += cost
      teacher.save!
      true
    else
      false
    end
  end

  private

  def set_pending_status
    self.status = STATUS::PENDING
  end

  def notify_teacher_about_new_lesson
    LessonMailer.new_lesson(self).deliver
  end

  def in_teacher_schedule
    beginning_of_week = start_at.beginning_of_week
    minutes_before_start = (start_at - beginning_of_week) / 60
    minutes_before_end = (end_at - beginning_of_week) / 60

    matched_schedules = teacher.schedules.where{ |schedules|
      (schedules.minutes_before_start <= minutes_before_start) &
      (schedules.minutes_before_end >= minutes_before_end)
    }

    unless matched_schedules.any?
      errors.add(:base, 'not in working time')
    end
  end

  def no_conflicts_with_other_lessons
    conflicted_lessons = teacher.lessons.where{ |lessons|
      (lessons.start_at < self.end_at) &
      (lessons.end_at > self.start_at) &
      (lessons.id != self.id)
    }

    if conflicted_lessons.any?
      errors.add(:base, 'conflict with other lesson')
    end
  end

  def not_earlier_than_tomorrow
    if start_at_changed? and (Time.now + 1.day > start_at)
      errors.add(:start_at, 'too early')
    end
  end

  def notify_about_canceling
    #return false unless status == STATUS::PENDING
    LessonMailer.lesson_canceled(self).deliver
    true
  end

  def withdraw_money
    student.balance -= cost
    student.save!
  end

  def student_has_enough_money
    if cost > student.balance
      errors.add(:base, 'not enough money')
    end
  end

  def should_not_be_completed
    if status == STATUS::COMPLETED
      errors.add(:base, 'lesson already completed')
    end
  end

  def return_money_to_student
    student.balance += cost
    student.save!
  end

end

app/controllers/lessons_controller.rb
class LessonsController < InheritedResources::Base
  load_and_authorize_resource
  respond_to :html, :json

  def index
    @lessons = current_user.lessons
    index!
  end

  def new
    @teacher = Teacher.find_by_id(params[:teacher_id])
    new!
  end

  def create
    @lesson = Lesson.new params[:lesson]
    @lesson.student = current_student
    create!
  end

  def accept
    if @lesson.update_attributes(status: Lesson::STATUS::UPCOMING)
      LessonMailer.lesson_accepted(@lesson).deliver
      redirect_to lessons_path, notice: 'Lesson request accepted'
    else
      redirect_to lessons_path, error: 'Lesson was not been accepted'
    end
  end

  def confirm
    if @lesson.complete
      redirect_to lessons_path, notice: 'Lesson marked as completed'
    else
      redirect_to lessons_path, error: 'Lesson was not been completed'
    end
  end

  def reschedule
    if @lesson.update_attributes(params[:lesson])
      @lesson.status = Lesson::STATUS::PENDING
      @lesson.save!
      LessonMailer.change_request(@lesson).deliver
    end
    respond_with @lesson
  end

end

app/views/lessons/_lesson_actions.html.haml
- if student_signed_in?
  - case @lesson.status
  - when Lesson::STATUS::UPCOMING
    = button_to 'Confirm lesson', confirm_lesson_path(@lesson),
      class: 'button success'

- if teacher_signed_in?
  - case @lesson.status
  - when Lesson::STATUS::PENDING
    = button_to 'Accept lesson', accept_lesson_path(@lesson),
      class: 'button success'

- if Lesson::STATUS::NOT_STARTED.include?(@lesson.status)
  = link_to 'Cancel this lesson', lesson_path(@lesson),
    method: :delete, class: 'button alert'

app/views/lessons/edit.html.haml
%h1 Editing lesson

= render 'form'

= link_to 'Show', @lesson
\|
= link_to 'Back', lessons_path

app/views/lessons/index.html.haml
%h2 Your lessons

%table.twelve
  %tr
    %th Start at
    %th End at
    %th Status
    %th Student
    %th Teacher
    %th

  - @lessons.each do |lesson|
    %tr
      %td= lesson.start_at
      %td= lesson.end_at
      %td= lesson.status
      %td= link_to lesson.student.name, lesson.student
      %td= link_to lesson.teacher.name, lesson.teacher
      %td= link_to 'View details', lesson

app/views/lessons/new.html.haml
%h2 Lesson scheduling
%p
  With teacher:
  %b= link_to @teacher.name, @teacher
%p
  Hourly rate:
  %b= number_to_currency @teacher.price

#lessons-picker

:javascript
  $(function(){
    var teacherId = #{ @teacher.id };
    var schedules = new App.Collections.Schedules({teacherId: teacherId});
    var lessons = new App.Collections.Lessons({teacherId: teacherId});
    // FIXME timezone issue
    schedules.reset(#{ @teacher.schedules.to_json(beginning_of_week: Time.now.beginning_of_week.advance(hours: 4)) });
    lessons.reset(#{ @teacher.lessons.to_json });
    var view = new App.Views.LessonsIndex({
      schedules: schedules,
      lessons: lessons
    });
    $('#lessons-picker').append(view.render().el).resize(); //FIXME
  });

= link_to 'Back', lessons_path

app/views/lessons/show.html.haml
%p From:
= @lesson.start_at

%p Until:
= @lesson.end_at

%p Status:
= @lesson.status

%p Student:
= link_to @lesson.student.name, @lesson.student

%p Teacher:
= link_to @lesson.teacher.name, @lesson.teacher

%p
= render 'lesson_actions'

= link_to 'Back', lessons_path, class: 'button secondary'