config/routes.rb
TeacherHelper::Application.routes.draw do

  resources :lessons do
    member do
      post 'confirm'
      post 'accept'
      put 'reschedule'
    end
  end

  resources :students, only: [:index, :show] do
    resource :balance, only: [:show, :edit, :update],
      controller: 'StudentBalance'
  end

  resources :teachers do
    resource :balance
    resources :schedules
  end


  devise_for :teachers, path_prefix: 'd'

  devise_for :students, path_prefix: 'd'

  root :to => 'home#index'
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert-box #{name == :notice ? "success" : "alert"}"}
    = msg
    %a.close(href='') &times;

app/views/layouts/_navigation.html.haml
%ul
  %li.name
    %h1
      = link_to 'Home', root_path
%section
  %ul.right
    - if teacher_signed_in?
      %li= link_to current_balance, '#'
      %li= link_to 'Dashboard', edit_teacher_path(current_teacher)
      %li= link_to 'Log out', destroy_teacher_session_path, method: :delete
      %li.has-dropdown
        %a(href='#')= current_teacher.name
        %ul.dropdown
          %li= link_to 'See profile', current_teacher
          %li= link_to 'Edit profile', edit_teacher_registration_path
          %li= link_to 'Log out', destroy_teacher_session_path, method: :delete
    - elsif student_signed_in?
      %li= link_to current_balance, student_balance_path(current_student)
      %li= link_to 'Dashboard', lessons_path
      %li.has-dropdown
        %a(href='#')= current_student.name
        %ul.dropdown
          %li= link_to 'See profile', current_student
          %li= link_to 'Edit profile', edit_student_registration_path
          %li= link_to 'Log out', destroy_student_session_path, method: :delete
    - else
      %li.has-dropdown
        %a(href='#') Student
        %ul.dropdown
          %li= link_to 'Student login', new_student_session_path
          %li= link_to 'Sign up', new_student_registration_path
      %li.has-dropdown
        %a(href='#') Teacher
        %ul.dropdown
          %li= link_to 'Teacher login', new_teacher_session_path
          %li= link_to 'Sign up', new_teacher_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Teacher Helper"
      %meta{:content => content_for?(:description) ? yield(:description) : "Teacher Helper", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        :coffeescript
          window.currentUser = #{current_user.to_json}
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .contain-to-grid
      %nav.top-bar
        = render 'layouts/navigation'
    .row
      .twelve.columns
        = render 'layouts/messages'
        = yield
    %footer

app/views/layouts/lesson_mailer.html.haml
!!!
%html
  %head
    %meta(content="text/html; charset=UTF-8" http-equiv="Content-Type")
  %body
    %h2 Hey!
    = yield