config/routes.rb
TeacherHelper::Application.routes.draw do

  resources :lessons do
    member do
      post 'confirm'
      post 'accept'
      put 'reschedule'
    end
  end

  resources :students, only: [:index, :show] do
    resource :balance, only: [:show, :edit, :update],
      controller: 'StudentBalance'
  end

  resources :teachers do
    resource :balance
    resources :schedules
  end


  devise_for :teachers, path_prefix: 'd'

  devise_for :students, path_prefix: 'd'

  root :to => 'home#index'
end

app/controllers/student_balance_controller.rb
class StudentBalanceController < ApplicationController
  load_and_authorize_resource :student
  respond_to :html

  def show
  end

  def edit
  end

  def update
    purchase_params = params[:purchase]
    # FIXME error exception looks weird
    error = @student.purchase(
      purchase_params[:amount].to_i, purchase_params[:credentials])
    if error
      flash.now[:error] = error
      render action: 'edit'
    else
      redirect_to student_balance_path, notice: 'Updated balance successfully'
    end
  end
end

app/views/student_balance/edit.html.haml
= simple_form_for :purchase, url: student_balance_path, method: 'PUT' do |f|
  = f.input :amount
  = f.fields_for :credentials do |ff|
    = ff.input :first_name
    = ff.input :last_name
    = ff.input :number
    = ff.input :month
    = ff.input :year
    = ff.input :verification_value
  = f.button :submit

app/views/student_balance/show.html.haml
%p Your balance: #{current_balance}
%p= link_to 'Add more', edit_student_balance_path,
  class: 'button success'